server:
  port: 8082

spring:
  application:
    name: cm-user
  main:
    allow-circular-references: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yc_project?serverTimezone=UTC
    username: root
    password: root

mybatis-plus:
  configuration:
    # 驼峰 - 下划线映射
    map-underscore-to-camel-case: true
  global-config:
    # 全局配置
    db-config:
      # id自增策略
      id-type: auto
      logic-delete-field: isDelete # 全局逻辑删除字段名
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值
  #如果在 Mapper 中有自定义方法，需要配置此项
  mapper-locations: classpath:/mapper/**.xml

knife4j:
  enable: true
  openapi:
    title: 校园集市
    description: "校园集市项目文档"
    email: xiaoymin@foxmail.com
    concat: 程序员羊皮
    url: https://docs.xiaominfo.com
    version: v1.0
    license: Apache 2.0
    license-url: https://stackoverflow.com/
    terms-of-service-url: https://stackoverflow.com/
    group:
      test1:
        group-name: 分组名称
        api-rule: package
        api-rule-resources:
          - com.project.controller